num1 = float(input('Digite um numero: '))
num2 = float(input('Digite outro numero: '))
print('==========')
soma = float(input('Faca a soma: '))
subtracao = float(input('Faca a subtracao: '))
multiplicacao = float(input('Faca a multiplicacao: '))
divisao = float(input('Faca a divisao: '))
print('==========')
print('Seu resultado:', soma, 'Resultado correto:', num1 + num2)
print('Seu resultado:', subtracao, 'Resultado correto:', num1 - num2)
print('Seu resultado:', multiplicacao, 'Resultado correto:', num1 * num2)
print('Seu resultado:', divisao, 'Resultado correto:', num1 / num2)