print('=============')
print('+++++Registration+++++')
print('=============')
name = input('Write your name:')
sob_name = input('Write your second name:')
age = input('Wirte your age:')
email = input('Write your E-mail:')
adress = input('Wirte your adress:')
city = input('Wirte your city:')
state = input('Wirte your state:')
prof = input('Wirte your profession:')
tel_num = input('Wirte your telephone number:')
marital = input('Wirte your marital status:')
national = input('Wirte your nationality:')
edu = input('Wirte your education:')
print('=============================')
print('Your name is', name, sob_name, '\nYou have', age, 'years old', '\nYour E-mail is', email, '\nYou lived in', adress, city, state, '\nYour profession is', prof, '\nYour telephone number is', tel_num, '\nYour marital status is', marital, '\nYour nationality is', national, '\nYour education is', edu)
